#    File: ~/.zshrc
#    Description: ZSH config
#    Author: Sarthak Dash


# Use powerline
USE_POWERLINE="true"

# Prompt
source ~/.config/zsh/zsh-prompt

# zsh-configuration
if [[ -e ~/.config/zsh/zsh-config ]]; then
  source ~/.config/zsh/zsh-config
fi

# Plugins
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# Autosuggest config
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'

# Aliases
alias zshrc="nvim ~/.zshrc"
alias v="nvim"
alias zupdate="source ~/.zshrc"
alias md2html="~/scripts/md2html/md2html.sh"
alias pl-dl="/home/sarthak/scripts/playlist-downloader.sh"
alias ls='exa --icons --color=always --group-directories-first'
alias ll='exa -alF --icons --color=always --group-directories-first'
alias la='exa -a --icons --color=always --group-directories-first'
alias l='exa -F --icons --color=always --group-directories-first'
alias l.='exa -a | egrep "^\."'
alias del='~/scripts/del.sh'

# Path
path+=('/home/sarthak/scripts')
path+=('/home/sarthak/.local/bin')
path+=('/home/sarthak/i3-apps/networkmanager-dmenu')
path+=('/home/sarthak/config/sway/scripts')

export PATH


# History config
HISTFILE=~/.config/zsh/histfile
HISTSIZE=10000
SAVEHIST=100000
