#Use powerline
USE_POWERLINE="true"
#Source manjaro-zsh-configuration
if [[ -e ~/.config/zsh/manjaro-zsh-config ]]; then
  source ~/.config/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
#if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
#  source /usr/share/zsh/manjaro-zsh-prompt
#fi
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'

source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
source ~/.config/zsh/zsh-prompt


# Aliases
alias zshrc="nvim ~/.zshrc"
alias v="nvim"
alias nenv="source ~/.config/nvim/bin/activate"
alias zupdate="source ~/.zshrc"
alias dact="deactivate"
alias cppgen="~/scripts/cpp-gen.sh"
alias cppc="~/scripts/cpp-compile.sh"
alias pyproject="~/scripts/pyproject.sh"



# Lines configured by zsh-newuser-install
HISTFILE=~/.config/zsh/histfile
HISTSIZE=10000
SAVEHIST=100000
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/sarthak/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# tilix issue
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi
